ALTER TABLE day_closings
  ADD COLUMN IF NOT EXISTS ms_other_lubes_qty NUMERIC(12, 3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ms_other_lubes_rate NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hsd_other_lubes_qty NUMERIC(12, 3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hsd_other_lubes_rate NUMERIC(12, 2) NOT NULL DEFAULT 0;
